server:
  port: 8380

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:18848
        ip: 127.0.0.1
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/cart/**
        # 订单请求转发到订单服务
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
        # 库存相关请求转发到商品服务
        - id: product-stock-service
          uri: lb://product-service
          predicates:
            - Path=/api/stock/**
        # 后台订单请求转发到订单服务
        - id: order-admin-service
          uri: lb://order-service
          predicates:
            - Path=/api/admin/order/**
        # 将认证相关请求转发到 auth-service
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        # 后台商品管理请求转发到商品服务
        - id: product-admin-service
          uri: lb://product-service
          predicates:
            - Path=/api/admin/**
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
