server:
  port: 8081

spring:
  application:
    name: product-service

management:
  endpoints:
    web:
      exposure:
        include: health,info

info:
  app:
    name: pinshengsheng-product-service
    description: 拼省省商品服务
