server:
  port: 8083

spring:
  application:
    name: cart-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:18848
        ip: 127.0.0.1

  data:
    redis:
      host: 127.0.0.1
      port: 16379
      timeout: 3s

management:
  endpoints:
    web:
      exposure:
        include: health,info
