server:
  port: 8383

spring:
  application:
    name: cart-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:18848
        ip: 127.0.0.1

  data:
    redis:
      host: 127.0.0.1
      port: 16379
      timeout: 3s
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: ${PSS_RABBITMQ_USERNAME:pinshengsheng}
    password: ${PSS_RABBITMQ_PASSWORD:pinshengsheng_rabbit_change_me}

management:
  endpoints:
    web:
      exposure:
        include: health,info
