server:
  port: 8383

spring:
  application:
    name: cart-service
  cloud:
    nacos:
      discovery:
        server-addr: ${PSS_NACOS_HOST:127.0.0.1}:${PSS_NACOS_PORT:18848}

  data:
    redis:
      host: ${PSS_REDIS_HOST:127.0.0.1}
      port: ${PSS_REDIS_PORT:16379}
      timeout: 3s
  rabbitmq:
    host: ${PSS_RABBITMQ_HOST:127.0.0.1}
    port: ${PSS_RABBITMQ_PORT:5672}
    username: ${PSS_RABBITMQ_USERNAME:pinshengsheng}
    password: ${PSS_RABBITMQ_PASSWORD:pinshengsheng_rabbit_change_me}

management:
  endpoints:
    web:
      exposure:
        include: health,info
